// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmkpreqqkbqcgrmidozx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJta3ByZXFxa2JxY2dybWlkb3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDQyMDcsImV4cCI6MjA3NDAyMDIwN30.H0mPuTpoq4kDy248IoMQRD_z4Ybeh7vCMjEdoRkY9wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});